### PR TITLE
STY: PEP8 changes and renaming of qvp variables.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by zssherman** [comment]
@meteoswiss-mdr I am taking another look at this and will try to work on adding unit tests. I completely forgot I did this PR.

**Comment by jfigui** [comment]
@zssherman , We appreciate that you are moving on this pull request but be aware that this repository is no longer maintained and there may have been changes in those functions. Please refer to https://github.com/MeteoSwiss/pyart from now on.

**Comment by zssherman** [comment]
Ah gotcha thanks for the heads up @jfigui! I'll close this PR and pull the commits from the branch you shared

**Comment by jfigui** [comment]
Hi @zssherman ,
Just to let you know that this repository is deprecated. The MeteoSwiss version of Py-ART is located here: https://github.com/MeteoSwiss/pyart

**Comment by zssherman** [comment]
@jfigui Sounds good, thanks for the heads up!

**Pull request closed without merging**
